name: wowbanner-new

services:
  nginx:
    image: ${REGISTRY}/api-wowbanner-nginx:${IMAGE_TAG}
    container_name: api-wowbanner-nginx
    restart: unless-stopped
    depends_on:
      - php-fpm
    networks:
      - proxy

  php-fpm:
    image: ${REGISTRY}/api-wowbanner-php-fpm:${IMAGE_TAG}
    container_name: api-wowbanner-php-fpm
    restart: unless-stopped
    env_file: .env
    networks:
      - proxy

  php-cli:
    image: ${REGISTRY}/api-wowbanner-php-cli:${IMAGE_TAG}
    container_name: api-wowbanner-php-cli
    restart: unless-stopped
    env_file: .env
    networks:
      - proxy

networks:
  proxy:
    external: true
