name: wowbanner-new

services:
  crm-app-wowbanner:
    container_name: crm-frontend-wowbanner
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "5174:5173"
    env_file: .env
    networks:
      - proxy

networks:
  proxy:
    external: true