; Production настройки opcache (оптимизированы для скорости)

; Проверка изменений файлов ОТКЛЮЧЕНА (для production)
opcache.validate_timestamps=0

; Частота проверки изменений (не важно, т.к. validate_timestamps=0)
opcache.revalidate_freq=60
