export const API_ENDPOINTS = {
  AUTH: {
    REFRESH: '/auth/refresh',
    LOGOUT: '/auth/logout',
  },
  USERS: {
    BY_ID: (id: string | number) => `/users/${id}`,
    SELECT: '/users/select',
  },
  CLIENTS: {
    LIST: '/clients',
    CREATE: '/clients/create',
    BY_ID: (id: string | number) => `/clients/${id}`,
    UPDATE: (id: string | number) => `/clients/update/${id}`,
    DELETE: (id: string | number) => `/clients/delete/${id}`,
    TYPES: '/clients/types',
    DOCS_TYPES: '/clients/docs-types',
    PHONE_TYPES: '/clients/phone-types',
  },
  MATERIALS: {
    LIST: '/materials',
    SELECT: '/materials/select',
    CREATE: '/materials/create',
    BY_ID: (id: string | number) => `/materials/${id}`,
    OPTION_SELECT: (id: string | number) => `/materials/${id}/options/select`,
    OPTION_DETAIL: (materialId: string | number, optionId: string | number) =>
      `/materials/${materialId}/option/${optionId}`,
    UPDATE: (id: string | number) => `/materials/update/${id}`,
    DELETE: (id: string | number) => `/materials/delete/${id}`,
    OPTION_PRICING_TYPES: '/materials/option-pricing-types',
    AREA_RANGE_TYPES: '/materials/area-range-types',
    DPI_TYPES: '/materials/dpi-types',
    VARIANT_TYPES: '/materials/variant-types',
    PRICING_CUT_TYPES: '/materials/pricing-cut-types',
    IMAGES: (materialId: string | number) => `/materials/${materialId}/images`,
    IMAGE_UPDATE: (imageId: string | number) => `/materials/images/${imageId}`,
    IMAGE_DELETE: (imageId: string | number) => `/materials/images/${imageId}`,
  },
  PROCESSINGS: {
    LIST: '/processings',
    CREATE: '/processings/create',
    BY_ID: (id: string | number) => `/processings/${id}`,
    UPDATE: (id: string | number) => `/processings/update/${id}`,
    DELETE: (id: string | number) => `/processings/delete/${id}`,
    TYPES: '/processings/types',
    SELECT: '/processings/select',
    IMAGES: (processingId: string | number) => `/processings/${processingId}/images`,
    IMAGE_UPDATE: (imageId: string | number) => `/processings/images/${imageId}`,
    IMAGE_DELETE: (imageId: string | number) => `/processings/images/${imageId}`,
  },
  PRINTINGS: {
    LIST: '/printings',
    SELECT: '/printings/select',
    CREATE: '/printings/create',
    BY_ID: (id: string | number) => `/printings/${id}`,
    UPDATE: (id: string | number) => `/printings/update/${id}`,
    DELETE: (id: string | number) => `/printings/delete/${id}`,
  },
  PRODUCTS: {
    LIST: '/products',
    SELECT: '/products/select',
    CREATE: '/products/create',
    BY_ID: (id: string | number) => `/products/${id}`,
    UPDATE: (id: string | number) => `/products/update/${id}`,
    DELETE: (id: string | number) => `/products/delete/${id}`,
  },
  ORDERS: {
    LIST: '/orders',
    CREATE: '/orders/create',
    BY_ID: (id: string | number) => `/orders/${id}`,
    UPDATE: (id: string | number) => `/orders/update/${id}`,
    DELETE: (id: string | number) => `/orders/delete/${id}`,
    FILE_DOWNLOAD: (id: string | number) => `/orders/files/${id}/download`,
    FILE_DELETE: (id: string | number) => `/orders/files/${id}`,
    STATUS_TYPES: '/orders/status-types',
    STORAGE_TYPES: '/orders/storage-types',
    DELIVERY_TYPES: '/orders/delivery-types',
    PAYMENT_OPERATION_TYPES: '/orders/payment-operation-types',
    PAYMENT_TYPES: '/orders/payment-types',
    SECTION_TYPES: '/orders/section-types',
    SERVICE_TYPES: '/orders/service-types',
  },
} as const;
